spring:
  application:
    name: "order-service"
  elasticsearch:
    rest:
      uris: "localhost:9200"

server:
  port: 5200
  servlet:
    context-path: "/api"
  # make sure the responses include error message so the client can understand his wrong api requests
  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: never

easysourcing:
  application-id: ${spring.application.name}
  bootstrap-servers: "localhost:9092"
  replicas: 1
  partitions: 1

logging:
  level:
    org:
      apache:
        kafka: warn
    com:
      github:
        easysourcing: debug
    io:
      github:
        alikelleci: debug
